[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"
  
[functions]
  memory = 1024
  node_bundler = "esbuild"
  external_node_modules = ["@sparticuz/chromium"]