[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
  package = "netlify-plugin-chromium"
  [plugins.inputs]
    packageManager = "yarn"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@sparticuz/chromium"]