import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import Providers from '@/lib/providers/Providers'

const poppins = Poppins({
    weight: ['400', '700'],
    subsets: ['latin'],
})

export const metadata: Metadata = {
    title: 'Home',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body className={`${poppins.className}`}>
                <Providers>{children}</Providers>
            </body>
        </html>
    )
}
